onboarding = false
[ui]
agent_panel_sort = "priority"
prompt_new_tab_name = false
pane_borders = true
pane_gaps = false

[ui.toast]
delivery = "herdr"
delay_seconds = 1

[terminal]
new_cwd = "follow"

[theme]
name = "dracula"
auto_switch = false

[worktrees]
directory = "~/.herdr/worktrees"

[keys]
prefix = "ctrl+space"
detach = "prefix+d"
reload_config = "prefix+r"
resize_mode = ""
split_vertical = "prefix+^"
focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
focus_pane_right = "alt+l"
previous_tab = "alt+shift+h"
next_tab = "alt+shift+l"

[[keys.command]]
key = "prefix+alt+g"
type = "pane"
command = "lazygit"
description = "run lazygit"
